### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by followthemoney1** [ar-android/DrawRouteMaps#6]
```
FATAL EXCEPTION: main
                                                                 java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;)V in class Lcom/google/android/gms/common/internal/zzaj; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaj' appears in /data/app/com.drovit.user-2/split_lib_dependencies_apk.apk:classes11.dex)
                                                                     at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
                                                                     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                                                                     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5255)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4806)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4746)
                                                                     at android.app.ActivityThread.access$1700(ActivityThread.java:153)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by followthemoney1** [comment]
fixed with `transitive = false`, can be closed
